baseURL = "https://example.com/"
languageCode = "en"
title = "Julian L端ken"
theme = "hugo-initio"
enableEmoji = true

[params]
    name = "Julian L端ken"
    description = "Putting the atoms back where they belong."
    email = ""
    phone = ""
    address = "With love from Antwerp, Belgium"
    year = 2024
    avatar = "images/guy2.jpg"
    avatarclass = "circle"
    background = ""
    banner = "images/antwerp.jpg"
    favicon = "images/gt_favicon2.png"
    DateForm = "January 2, 2006"
    author = "Julian L端ken"

    showSubheader = true
    showServices = true
    showRecentWorks = true
    showDownloads = false
    showClients = true

    showFooterContact = false
    showFooterFollowMe = true
    showFooterTextWidget = false
    showFooterFormWidget = false

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "ORCID"
    url = "https://orcid.org/0009-0009-4264-6735"
    weight = 5000

#[params.disqus]
    #site = "hugo-initio-site.disqus.com"

#[params.sharethis]
    #property = "123456789012345678901234"
    #custom = true

#[params.google.analytics]
    #trackerID = "GA-000000000-0"

[[params.social]]
	title = "facebook"
	url = "https://www.facebook.com/nickname"
    icon = "fab fa-facebook-square"
    footer = false
    sharethis = true
    network = "facebook"
[[params.social]]
	title = "twitter"
	url = "https://twitter.com/nickname"
    icon = "fab fa-twitter-square"
    footer = false
    sharethis = true
    network = "twitter"
[[params.social]]
	title = "instagram"
	url = "https://www.instagram.com/nickname"
    icon = "fab fa-instagram"
    footer = false
    sharethis = false
    network = ""
[[params.social]]
	title = "google+"
	url = "https://plus.google.com/+nickname"
    icon = "fab fa-google-plus-square"
    footer = false
    sharethis = true
    network = "googleplus"
[[params.social]]
	title = "linkedin"
	url = "https://linkedin.com/in/julian-l端ken-b11310298"
    icon = "fab fa-linkedin"
    footer = true
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "tumblr"
	url = "https://nickname.tumblr.com"
    icon = "fab fa-tumblr-square"
    footer = false
    sharethis = false
    network = "tumblr"
[[params.social]]
	title = "github"
	url = "https://github.com/boolean-julian"
    icon = "fab fa-github"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "email"
	url = "mailto:julian.luken@uantwerp.be"
    icon = "fas fa-envelope-square"
    footer = true
    sharethis = true
    network = "email"
